### ISSUE TITLE
Export Default

### ISSUE THREAD

**Issue by NArnott** [CapnMarius/EventAggregator#1]
Having EventAggregator declared as Export Default breaks angular (see https://stackoverflow.com/questions/48183594/invalid-provider-for-the-ngmodule-when-using-aot). Could that be made as a named exportable, just like everything else?

**Comment by CapnMarius** [comment]
Sure, I'll publish a new version on monday.

**Comment by CapnMarius** [comment]
@NArnott Implemented in version 1.2.0 👍

**Comment by NArnott** [comment]
Awesome! Thx
